spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    user: ${POSTGRES_PASSWORD}
    password: ${POSTGRES_PASSWORD}
    baseline-on-migrate: true

logging:
  level:
    org.springframework:
      data:
        r2dbc: DEBUG

jwt:
  header: Authorization
  param: token
  secret: m6sXDUKZSY154e9N
  expiration: 86400000
  prefix: Bearer
  route:
    authentication:
      path: auth
      token: token
      refresh: refresh
